//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelSP2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelSP2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Selection { get { return ResourceManager.GetString("Selection", resourceCulture); } }
        public static string Capture { get { return ResourceManager.GetString("Capture", resourceCulture); } }
        public static string Preview { get { return ResourceManager.GetString("Preview", resourceCulture); } }
        public static string Reset { get { return ResourceManager.GetString("Reset", resourceCulture); } }
        public static string NoSelectionCaptured { get { return ResourceManager.GetString("NoSelectionCaptured", resourceCulture); } }
        public static string ContextMaterials { get { return ResourceManager.GetString("ContextMaterials", resourceCulture); } }
        public static string PasteImagesText { get { return ResourceManager.GetString("PasteImagesText", resourceCulture); } }
        public static string Prompt { get { return ResourceManager.GetString("Prompt", resourceCulture); } }
        public static string Save { get { return ResourceManager.GetString("Save", resourceCulture); } }
        public static string DataWrite { get { return ResourceManager.GetString("DataWrite", resourceCulture); } }
        public static string DataOp { get { return ResourceManager.GetString("DataOp", resourceCulture); } }
        public static string ReferenceExistingData { get { return ResourceManager.GetString("ReferenceExistingData", resourceCulture); } }
        public static string MacroLibrary { get { return ResourceManager.GetString("MacroLibrary", resourceCulture); } }
        public static string Run { get { return ResourceManager.GetString("Run", resourceCulture); } }
        public static string VBENote { get { return ResourceManager.GetString("VBENote", resourceCulture); } }
        public static string Settings { get { return ResourceManager.GetString("Settings", resourceCulture); } }
        public static string GenerateAndFill { get { return ResourceManager.GetString("GenerateAndFill", resourceCulture); } }
        public static string Ready { get { return ResourceManager.GetString("Ready", resourceCulture); } }
        public static string PromptManagement { get { return ResourceManager.GetString("PromptManagement", resourceCulture); } }
        public static string Prompts { get { return ResourceManager.GetString("Prompts", resourceCulture); } }
        public static string Add { get { return ResourceManager.GetString("Add", resourceCulture); } }
        public static string Delete { get { return ResourceManager.GetString("Delete", resourceCulture); } }
        public static string Title { get { return ResourceManager.GetString("Title", resourceCulture); } }
        public static string Content { get { return ResourceManager.GetString("Content", resourceCulture); } }
        public static string SaveChanges { get { return ResourceManager.GetString("SaveChanges", resourceCulture); } }
        public static string VBAMacroManagement { get { return ResourceManager.GetString("VBAMacroManagement", resourceCulture); } }
        public static string LocalMacros { get { return ResourceManager.GetString("LocalMacros", resourceCulture); } }
        public static string Import { get { return ResourceManager.GetString("Import", resourceCulture); } }
        public static string InFileMacros { get { return ResourceManager.GetString("InFileMacros", resourceCulture); } }
        public static string Code { get { return ResourceManager.GetString("Code", resourceCulture); } }
        public static string LLMManagement { get { return ResourceManager.GetString("LLMManagement", resourceCulture); } }
        public static string LocalModelDetection { get { return ResourceManager.GetString("LocalModelDetection", resourceCulture); } }
        public static string DetectLocalModels { get { return ResourceManager.GetString("DetectLocalModels", resourceCulture); } }
        public static string Mode { get { return ResourceManager.GetString("Mode", resourceCulture); } }
        public static string SimpleSettings { get { return ResourceManager.GetString("SimpleSettings", resourceCulture); } }
        public static string AdvancedSettings { get { return ResourceManager.GetString("AdvancedSettings", resourceCulture); } }
        public static string SimpleModeNote { get { return ResourceManager.GetString("SimpleModeNote", resourceCulture); } }
        public static string Provider { get { return ResourceManager.GetString("Provider", resourceCulture); } }
        public static string ApiUrl { get { return ResourceManager.GetString("ApiUrl", resourceCulture); } }
        public static string ApiKey { get { return ResourceManager.GetString("ApiKey", resourceCulture); } }
        public static string Model { get { return ResourceManager.GetString("Model", resourceCulture); } }
        public static string HeaderDetection { get { return ResourceManager.GetString("HeaderDetection", resourceCulture); } }
        public static string RequiresMultimodal { get { return ResourceManager.GetString("RequiresMultimodal", resourceCulture); } }
        public static string DataWriteSection { get { return ResourceManager.GetString("DataWriteSection", resourceCulture); } }
        public static string DataOperation { get { return ResourceManager.GetString("DataOperation", resourceCulture); } }
        public static string TextOnlySufficient { get { return ResourceManager.GetString("TextOnlySufficient", resourceCulture); } }
        public static string VBAEnvironmentDetection { get { return ResourceManager.GetString("VBAEnvironmentDetection", resourceCulture); } }
        public static string TextOnlySufficientSimple { get { return ResourceManager.GetString("TextOnlySufficientSimple", resourceCulture); } }
        public static string OK { get { return ResourceManager.GetString("OK", resourceCulture); } }
        public static string Cancel { get { return ResourceManager.GetString("Cancel", resourceCulture); } }
        public static string SelectedInfo { get { return ResourceManager.GetString("SelectedInfo", resourceCulture); } }
        public static string HeaderCached { get { return ResourceManager.GetString("HeaderCached", resourceCulture); } }
        public static string AppTitle { get { return ResourceManager.GetString("AppTitle", resourceCulture); } }
    }
}
